import "./globals.css";
import Link from "next/link";
import LogoutButton from "@/components/LogoutButton";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import Layout from "../layout/Layout";
import Header from "../layout/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic'
 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  // user: React.ReactNode;
}) {

  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          {user ? (
            <main>
              <Header title="Kekw" />
              <Layout>
                <div>
                  Hey, {user.email}!
                  <LogoutButton />
                </div>
                <Link href="/Todo">Todos</Link>
              </Layout>
            </main>
          ) : (
            <Link href="/login">Login</Link>
          )}
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}


