import DeployButton from "@/components/DeployButton";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "@/components/LogoutButton";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <main>
            <nav>
              <div>
                {user ? (
                  <div>
                    Hey, {user.email}!
                    <LogoutButton />
                  </div>
                ) : (
                  <Link href="/login">Login</Link>
                )}
              </div>
            </nav>
            {children}
          </main>
        </body>
      </ThemeRegistry>
    </html>
  );
}
